theme: jekyll-theme-cayman

# Config
title: Sheikh Saad Abdullah
description: All about me!
show_links: true
links:
    github: https://github.com/cybardev
    projects: null
    resume: https://me.cybar.dev/assets/resume.pdf
    blog: https://cybar.dev

show_projects: true
projects:
    ytpy:
        repo: ytpy
        url: https://github.com/cybardev/ytpy
        desc: CLI YouTube Media Player
    search:
        repo: search
        url: https://github.com/cybardev/search
        desc: Custom Search Engine using the Usearch API
    xpense:
        repo: xpense
        url: https://github.com/cybardev/xpense
        desc: Monthly Expense Calculator for Budgeting
    cutefetch:
        repo: cutefetch
        url: https://github.com/cybardev/cutefetch
        desc: Cute little fetch script with kitties and bunnies
