# Setup
title: Sheikh Saad Abdullah
tagline: All about me!
baseurl: "https://me.cybar.dev/"

# About/contact
author:
    name: Sheikh Saad Abdullah
    url: http://cybar.dev/

#Others
theme: jekyll-theme-cayman
