theme: jekyll-theme-cayman
markdown: kramdown

# Site
title: Sheikh Saad Abdullah
description: Software Developer | interested in DevOps and Cloud | Pixel Artist
show_links: true
links:
    linkedin: https://www.linkedin.com/in/cybardev
    github: https://github.com/cybardev
    blog: https://blog.cybar.dev

# Projects
show_projects: true
projects:
    resumake: Programmatic resume generator
    ytgo: Find and watch YouTube videos from terminal without needing API keys
    prayers: Islamic prayer times API and example front-end consumer
    CybarPass: Random Password Generator with GUI
    blog: Full-stack accessible blog with CMS for client at Northwood
    cutefetch: Cute little fetch script with kitties and bunnies
    zen.zsh: Simple and Elegant Prompt for Zsh
    search: Custom Search Engine using the Usearch API
