theme: jekyll-theme-cayman
markdown: kramdown

# Site
title: Sheikh Saad Abdullah
description: All about me!
show_links: true
links:
    github: https://github.com/cybardev
    resume: https://me.cybar.dev/assets/resume.pdf
    blog: https://cybar.dev

# Projects
show_projects: true
projects:
    ytpy: CLI YouTube Media Player
    cutefetch: Cute little fetch script with kitties and bunnies
    search: Custom Search Engine using the Usearch API
    xpense: Monthly Expense Calculator for Budgeting
    zen.zsh: Simple and Elegant Prompt for Zsh
