theme: jekyll-theme-cayman

# Config
title: Sheikh Saad Abdullah
description: All about me!
show_links: true
links:
    github: https://github.com/cybardev
    projects: null
    resume: https://me.cybar.dev/assets/resume.pdf
    blog: https://cybar.dev

show_projects: true
projects:
    ytpy:
        name: ytpy
        desc: CLI YouTube Media Player
    search:
        name: search
        desc: Custom Search Engine using the Usearch API
    xpense:
        name: xpense
        desc: Monthly Expense Calculator for Budgeting
    cutefetch:
        name: cutefetch
        desc: Cute little fetch script with kitties and bunnies
