theme: jekyll-theme-cayman

# Config
title: Sheikh Saad Abdullah
description: All about me!
show_links: true
links:
    projects: null
    resume: https://me.cybar.dev/assets/resume.pdf
    blog: https://cybar.dev/
