theme: jekyll-theme-cayman

# Site
title: Sheikh Saad Abdullah
description: All about me!
show_links: true
links:
    github: https://github.com/cybardev
    projects: null
    resume: https://me.cybar.dev/assets/resume.pdf
    blog: https://cybar.dev

# Projects
show_projects: true
projects:
    - ytpy
    - search
    - xpense
    - cutefetch
project_descriptions:
    ytpy: CLI YouTube Media Player
    search: Custom Search Engine using the Usearch API
    xpense: Monthly Expense Calculator for Budgeting
    cutefetch: Cute little fetch script with kitties and bunnies
