theme: jekyll-theme-cayman
markdown: kramdown

# Site
title: Sheikh Saad Abdullah
description: Aspiring Front-end Web Developer and Avid Tech Enthusiast
show_links: true
links:
    github: https://github.com/cybardev
    resume: https://link.cybar.dev/resume
    blog: https://blog.cybar.dev

# Projects
show_projects: true
projects:
    ytpy: CLI YouTube Media Player
    cutefetch: Cute little fetch script with kitties and bunnies
    search: Custom Search Engine using the Usearch API
    zen.zsh: Simple and Elegant Prompt for Zsh
    xpense: Monthly Expense Calculator for Budgeting
    dotfiles: Configuration files for my MacOS setup
